name: Whisper Valley Railroad
favicon: null
layout_spectrum: 0.23413
typography_spectrum: 0.57246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f2f2f'
    - '#c3ced2'
    - '#5b5853'
    - '#89292c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
