typography_spectrum: 0.57246
color:
  brandColors:
    - '#ffffff'
    - '#2f2f2f'
    - '#c3ced2'
    - '#5b5853'
    - '#89292c'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44806
analytics:
  google: null
  facebook: null
  twitter: null
name: Whisper Valley Railroad
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
